baseURL: https://jakryd.github.io/
languageCode: en-us
title: JR's Research
theme: vanilla-bootstrap-hugo-theme
publishDir: docs

menu:
  nav:
  - name: Home
    url: /
    weight: 1
  - name: Publications
    url: /publications/
    weight: 3
  - name: Software
    url: /software/
    weight: 4
  - name: Group
    url: /group/
    weight: 2

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: 
  footerText: Made with [Hugo](https://gohugo.io/)  
  hideFooter: false
  katex: true
  plugins:
    css:
      - URL: plugins/academicons/css/academicons.css

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
