baseURL: https://jakryd.github.io
languageCode: en-us
title: jr
theme: vanilla-bootstrap-hugo-theme

taxonomies:
  tag: tags

menu:
  nav:
  - name: Home
    url: /
    weight: 1
  - name: Publications
    url: /publications/
    weight: 2
  - name: Software
    url: /software/
    weight: 3
  - name: About
    url: /about/
    weight: 4

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: Welcome to the Vanilla theme demo. Have a look around. Maybe even eat some ice cream.
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2

